# Generated by Django 3.1.7 on 2021-03-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
                ('quarantine', models.IntegerField()),
                ('room', models.IntegerField()),
                ('num_quarantine', models.IntegerField()),
                ('num_free', models.IntegerField()),
                ('start', models.DateTimeField()),
            ],
        ),
    ]
